// Hand-curated LeafGreen progression order for PokeAPI location
// identifiers, since PokeAPI has no notion of in-game reachability order.
// Route granularity is per-location, not per-location-area: the game shows
// one banner name per location regardless of which floor/sub-area you're
// on (e.g. Mt. Moon's 3 floors all just say "Mt. Moon"), matching nuzlocke
// convention of one encounter per named area. Verified (2026-08-02,
// re-verified 2026-08-03 after collapsing to location granularity) against
// the live PokeAPI: every location with at least one "leafgreen"
// wild/fixed encounter is listed here exactly once, in real story order —
// mainland Kanto (Pallet Town through Victory Road), then postgame
// (Cerulean Cave, Kanto Altering Cave, roaming legendaries), then the
// Sevii Islands (One through Seven Island in story order), then
// event-only locations (Birth Island, Navel Rock).
export const LEAFGREEN_ROUTE_ORDER: readonly string[] = [
  "pallet-town",
  "kanto-route-1",
  "viridian-city",
  "kanto-route-22",
  "kanto-route-2",
  "viridian-forest",
  "kanto-route-3",
  "mt-moon",
  "kanto-route-4",
  "cerulean-city",
  "kanto-route-24",
  "kanto-route-25",
  "kanto-route-5",
  "kanto-route-6",
  "vermilion-city",
  "ss-anne",
  "kanto-route-11",
  "digletts-cave",
  "kanto-route-9",
  "kanto-route-10",
  "kanto-power-plant",
  "rock-tunnel",
  "pokemon-tower",
  "kanto-route-8",
  "kanto-route-7",
  "celadon-city",
  "kanto-route-16",
  "kanto-route-17",
  "kanto-route-18",
  "fuchsia-city",
  "kanto-safari-zone",
  "kanto-route-15",
  "kanto-route-14",
  "kanto-route-13",
  "kanto-route-12",
  "saffron-city",
  "kanto-sea-route-19",
  "kanto-sea-route-20",
  "seafoam-islands",
  "cinnabar-island",
  "pokemon-mansion",
  "kanto-sea-route-21",
  "kanto-route-23",
  "kanto-victory-road-2",
  "cerulean-cave",
  "kanto-altering-cave",
  "roaming-kanto",
  "kanto-pokecenter",
  "one-island",
  "kindle-road",
  "mt-ember",
  "trainer-tower",
  "three-isle-port",
  "berry-forest",
  "bond-bridge",
  "cape-brink",
  "four-island",
  "icefall-cave",
  "five-island",
  "five-isle-meadow",
  "memorial-pillar",
  "resort-gorgeous",
  "water-labyrinth",
  "treasure-beach",
  "lost-cave",
  "pattern-bush",
  "green-path",
  "water-path",
  "outcast-island",
  "ruin-valley",
  "canyon-entrance",
  "sevault-canyon",
  "tanoby-ruins",
  "monean-chamber",
  "liptoo-chamber",
  "weepth-chamber",
  "dilford-chamber",
  "scufib-chamber",
  "rixy-chamber",
  "viapos-chamber",
  "birth-island",
  "navel-rock",
];
